version: '3'
services:

  dbserver:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: user_auth_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
      MYSQL_ROOT_PASSWORD: root

  api:
    image: 057663277679.dkr.ecr.ap-northeast-1.amazonaws.com/nitta-authapi:latest
    depends_on:
      - dbserver
    ports:
      - "8080:8080"
    environment:
      JAR_TARGET: userAuthAPI-0.0.1-SNAPSHOT.jar

volumes:
  mysql-db:
    driver: local

